services:
  rz-app:
    build: .
    container_name: rz-app
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    restart: unless-stopped
